### ISSUE TITLE
No inner_progress_color

### ISSUE THREAD

**Issue by XtheWiz** [Flepsik/ProgressRingView#3]
Hi, thank you for the nice progress ring indicator. I would like to apply this into my app.
But unfortunately, I just copy and paste the XML example into my layout and build it, I got the error below:

**Error:(11) No resource identifier found for attribute 'inner_progress_color' in package 'com.chubbycatstudio.smarttimeattendance'**

**Comment by Flepsik** [comment]
renamed methods and attributes related to inner progress
